# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file '메모장ZoTrbQ.ui'
##
## Created by: Qt User Interface Compiler version 6.1.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(700, 500)
        self.action = QAction(MainWindow)
        self.action.setObjectName(u"action")
        self.action_2 = QAction(MainWindow)
        self.action_2.setObjectName(u"action_2")
        self.actionzxc = QAction(MainWindow)
        self.actionzxc.setObjectName(u"actionzxc")
        self.actionASD = QAction(MainWindow)
        self.actionASD.setObjectName(u"actionASD")
        self.actioncnrth = QAction(MainWindow)
        self.actioncnrth.setObjectName(u"actioncnrth")
        self.actionghkrreogkrl_cntrh = QAction(MainWindow)
        self.actionghkrreogkrl_cntrh.setObjectName(u"actionghkrreogkrl_cntrh")
        self.actionn = QAction(MainWindow)
        self.actionn.setObjectName(u"actionn")
        self.new_window = QAction(MainWindow)
        self.new_window.setObjectName(u"new_window")
        self.actione_2 = QAction(MainWindow)
        self.actione_2.setObjectName(u"actione_2")
        self.actione_3 = QAction(MainWindow)
        self.actione_3.setObjectName(u"actione_3")
        self.actione_4 = QAction(MainWindow)
        self.actione_4.setObjectName(u"actione_4")
        self.actione_5 = QAction(MainWindow)
        self.actione_5.setObjectName(u"actione_5")
        self.actione_6 = QAction(MainWindow)
        self.actione_6.setObjectName(u"actione_6")
        self.actione_7 = QAction(MainWindow)
        self.actione_7.setObjectName(u"actione_7")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setMaximumSize(QSize(800, 557))
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.plainTextEdit = QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setObjectName(u"plainTextEdit")

        self.gridLayout.addWidget(self.plainTextEdit, 0, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 700, 22))
        self.menu_F = QMenu(self.menubar)
        self.menu_F.setObjectName(u"menu_F")
        self.menu_E = QMenu(self.menubar)
        self.menu_E.setObjectName(u"menu_E")
        self.menu_O = QMenu(self.menubar)
        self.menu_O.setObjectName(u"menu_O")
        self.menu_V = QMenu(self.menubar)
        self.menu_V.setObjectName(u"menu_V")
        self.menu = QMenu(self.menu_V)
        self.menu.setObjectName(u"menu")
        self.menu_H = QMenu(self.menubar)
        self.menu_H.setObjectName(u"menu_H")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menu_F.menuAction())
        self.menubar.addAction(self.menu_E.menuAction())
        self.menubar.addAction(self.menu_O.menuAction())
        self.menubar.addAction(self.menu_V.menuAction())
        self.menubar.addAction(self.menu_H.menuAction())
        self.menu_F.addAction(self.actionn)
        self.menu_F.addAction(self.new_window)
        self.menu_F.addAction(self.actione_2)
        self.menu_F.addAction(self.actione_3)
        self.menu_F.addAction(self.actione_4)
        self.menu_F.addSeparator()
        self.menu_F.addAction(self.actione_5)
        self.menu_F.addAction(self.actione_6)
        self.menu_F.addSeparator()
        self.menu_F.addAction(self.actione_7)
        self.menu_V.addAction(self.menu.menuAction())
        self.menu_V.addAction(self.actionzxc)
        self.menu.addAction(self.actionASD)
        self.menu.addAction(self.actioncnrth)
        self.menu.addAction(self.actionghkrreogkrl_cntrh)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.action.setText(QCoreApplication.translate("MainWindow", u"\uae30", None))
        self.action_2.setText(QCoreApplication.translate("MainWindow", u"\u3141", None))
        self.actionzxc.setText(QCoreApplication.translate("MainWindow", u"\uc0c1\ud0dc\ud45c\uc2dc\uc904(S)", None))
        self.actionASD.setText(QCoreApplication.translate("MainWindow", u"\ud655\ub300(I)", None))
        self.actioncnrth.setText(QCoreApplication.translate("MainWindow", u"\ucd95\uc18c(O)", None))
        self.actionghkrreogkrl_cntrh.setText(QCoreApplication.translate("MainWindow", u"\ud655\ub300\ud558\uae30/\ucd95\uc18c\ud558\uae30 \uae30\ubcf8\uac12 \ubcf5\uc6d0", None))
        self.actionn.setText(QCoreApplication.translate("MainWindow", u"\uc0c8\ub85c \ub9cc\ub4e4\uae30(N)", None))
#if QT_CONFIG(shortcut)
        self.actionn.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.new_window.setText(QCoreApplication.translate("MainWindow", u"\uc0c8 \ucc3d(W)", None))
#if QT_CONFIG(shortcut)
        self.new_window.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+W", None))
#endif // QT_CONFIG(shortcut)
        self.actione_2.setText(QCoreApplication.translate("MainWindow", u"\uc5f4\uae30(O)...", None))
#if QT_CONFIG(shortcut)
        self.actione_2.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actione_3.setText(QCoreApplication.translate("MainWindow", u"\uc800\uc7a5(S)", None))
#if QT_CONFIG(shortcut)
        self.actione_3.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actione_4.setText(QCoreApplication.translate("MainWindow", u"\ub2e4\ub978 \uc774\ub984\uc73c\ub85c \uc800\uc7a5(A)...", None))
#if QT_CONFIG(shortcut)
        self.actione_4.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+A", None))
#endif // QT_CONFIG(shortcut)
        self.actione_5.setText(QCoreApplication.translate("MainWindow", u"\ud398\uc774\uc9c0 \uc124\uc815(U)...", None))
#if QT_CONFIG(shortcut)
        self.actione_5.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+U", None))
#endif // QT_CONFIG(shortcut)
        self.actione_6.setText(QCoreApplication.translate("MainWindow", u"\uc778\uc1c4(P)...", None))
#if QT_CONFIG(shortcut)
        self.actione_6.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+P", None))
#endif // QT_CONFIG(shortcut)
        self.actione_7.setText(QCoreApplication.translate("MainWindow", u"\ub05d\ub0b4\uae30(X)", None))
#if QT_CONFIG(shortcut)
        self.actione_7.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+X", None))
#endif // QT_CONFIG(shortcut)
        self.menu_F.setTitle(QCoreApplication.translate("MainWindow", u"\ud30c\uc77c(F)", None))
        self.menu_E.setTitle(QCoreApplication.translate("MainWindow", u"\ud3b8\uc9d1(E)", None))
        self.menu_O.setTitle(QCoreApplication.translate("MainWindow", u"\uc11c\uc2dd(O)", None))
        self.menu_V.setTitle(QCoreApplication.translate("MainWindow", u"\ubcf4\uae30(V)", None))
        self.menu.setTitle(QCoreApplication.translate("MainWindow", u"\ud655\ub300\ud558\uae30/\ucd95\uc18c\ud558\uae30", None))
        self.menu_H.setTitle(QCoreApplication.translate("MainWindow", u"\ub3c4\uc6c0\ub9d0(H)", None))
    # retranslateUi

